language: node_js
node_js:
  - 12.16
notifications:
  slack: devpartners-io:SLtbju2Qy2gpKF1zoyU1gJJz
env:
  - APP_ENV=testing
install:
  - yarn install
script:
  - yarn run prod
after_success:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git status
  - git add css/*.css
  - git add js/*.js
  - git remote add origin https://${GH_TOKEN}@github.com/dev-partners/devpartners.io.git > /dev/null 2>&1
  - git commit --message "Travis asset build"
  - git push origin $TRAVIS_BRANCH
  - echo "Success"