language: ruby
rvm:
  - 2.6.3
notifications:
  slack: devpartners-io:SLtbju2Qy2gpKF1zoyU1gJJz
env:
  - APP_ENV=testing
install:
  - gem install jekyll
before_script:
  - jekyll build
script:
  - yarn run prod
after_success:
  - echo "Success"