exclude: ['resources', 'package.json', 'yarn.lock', 'package-lock.json', 'mix-manifest.json', 'tailwind.config.js', 'webpack.mix.js', '.idea', 'resources']
plugins: [jekyll-paginate]
permalink: /:categories/:year/:month/:day/:title
include: ['_pages']
paginate: 18
paginate_path: "/blog/:num"
collections:
  team:
    output: true
    permalink: /blog/authors/:name
  opportunities:
    output: true
    permalink: /careers/opportunities/:name

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "blog"
  - scope:
      path: ""
      type: "opportunities"
    values:
      layout: "opportunities"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "articles"
excerpt_separator: <!--more-->
