backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "img/uploads"
collections:
  - name: "posts"
    label: "Posts"
    create: true
    folder: "_posts"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Post Author"
        name: "author"
        widget: "relation"
        collection: "team"
        searchFields: ["name"]
        valueField: "id"
        displayFields: ["name"]
      - label: "Main Image"
        name: "main_image"
        widget: "image"
      - label: "Photo Credit"
        name: "photo_credit"
        widget: "string"
  - name: "team"
    label: "Team"
    folder: "_team"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Display Position", name: "position", widget: "number"}
      - {label: "Photo", name: "photo", widget: "image"}
      - {label: "Social Links", name: "social", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}